const modules = [
  {id:'fondamentaux',icon:'◉',title:'Fondamentaux de la transfusion',duration:'20 min',desc:'Comprendre la chaîne transfusionnelle, ses acteurs et ses principes de sécurité.'},
  {id:'psl',icon:'◒',title:'Produits sanguins labiles',duration:'25 min',desc:'Identifier les CGR, le plasma et les concentrés plaquettaires.'},
  {id:'compatibilite',icon:'⇄',title:'Compatibilité transfusionnelle',duration:'25 min',desc:'Revoir les systèmes ABO et Rhésus ainsi que les contrôles biologiques.'},
  {id:'securisation',icon:'✓',title:'Sécurisation avant transfusion',duration:'20 min',desc:'Appliquer une checklist structurée avant le branchement.'},
  {id:'incidents',icon:'!',title:'Incidents transfusionnels',duration:'35 min',desc:'Reconnaître les signes d’alerte et organiser la conduite à tenir.'},
  {id:'hemovigilance',icon:'◎',title:'Hémovigilance & traçabilité',duration:'20 min',desc:'Comprendre le signalement, l’enquête et la traçabilité.'}
];
const nav = [
  ['accueil','⌂','Accueil'],['formation','▤','Formation'],['cas','◇','Cas pratiques'],['quiz','?','Quiz final'],['fiches','▣','Fiches pratiques'],['glossaire','A','Glossaire'],['ressources','↗','Ressources'],['parcours','◔','Mon parcours']
];
const incidents = [
  {name:'Réaction allergique',level:'Modéré',cls:'moderate',signs:'Urticaire, prurit, rougeurs, parfois gêne respiratoire.',definition:'Réaction d’hypersensibilité survenant pendant ou peu après la transfusion.'},
  {name:'Réaction fébrile non hémolytique',level:'Modéré',cls:'moderate',signs:'Fièvre, frissons, malaise, sans preuve immédiate d’hémolyse.',definition:'Élévation thermique associée à la transfusion, diagnostic posé après exclusion d’autres causes.'},
  {name:'Réaction hémolytique aiguë / incompatibilité ABO',level:'Urgence vitale',cls:'vital',signs:'Fièvre, frissons, douleur lombaire, hypotension, urines foncées.',definition:'Destruction rapide des globules rouges transfusés, notamment lors d’une incompatibilité.'},
  {name:'Suspicion d’infection bactérienne',level:'Urgent',cls:'urgent',signs:'Fièvre élevée, frissons intenses, hypotension, choc.',definition:'Réaction potentiellement liée à une contamination du produit ; nécessite une investigation immédiate.'},
  {name:'TRALI',level:'Urgence vitale',cls:'vital',signs:'Dyspnée aiguë, hypoxémie, détresse respiratoire, infiltrats pulmonaires.',definition:'Atteinte pulmonaire aiguë associée à la transfusion, sans argument principal pour une surcharge.'},
  {name:'TACO',level:'Urgence vitale',cls:'vital',signs:'Dyspnée, hypertension possible, œdème pulmonaire, signes de surcharge.',definition:'Surcharge circulatoire associée à la transfusion, favorisée par un débit ou volume mal toléré.'},
  {name:'Réaction anaphylactique',level:'Urgence vitale',cls:'vital',signs:'Détresse respiratoire, hypotension, œdème, signes cutanés possibles.',definition:'Réaction allergique systémique sévère d’installation rapide.'},
  {name:'Hypotension associée à la transfusion',level:'Urgent',cls:'urgent',signs:'Chute tensionnelle isolée ou associée à un malaise.',definition:'Baisse aiguë de la pression artérielle pendant la transfusion, après recherche d’une autre cause.'}
];
const glossary = [
 ['ABO','Système de groupes sanguins fondé sur la présence des antigènes A et B à la surface des globules rouges.'],
 ['CGR','Concentré de globules rouges, produit utilisé pour restaurer la capacité de transport de l’oxygène.'],
 ['PSL','Produit sanguin labile : composant issu du sang destiné à la transfusion.'],
 ['RAI','Recherche d’agglutinines irrégulières, examen détectant certains anticorps anti-érythrocytaires.'],
 ['Rhésus','Système de groupe sanguin dont l’antigène D est le plus couramment pris en compte.'],
 ['TRALI','Atteinte pulmonaire aiguë associée à la transfusion.'],
 ['TACO','Surcharge circulatoire associée à la transfusion.'],
 ['Hémovigilance','Surveillance, évaluation et prévention des événements indésirables liés à la chaîne transfusionnelle.'],
 ['Traçabilité','Capacité à relier le produit, le donneur, le receveur et les étapes du processus.'],
 ['Compatibilité','Adéquation immuno-hématologique entre le produit sanguin et le receveur.']
];
const quiz = [
 {q:'Quelle est la première action face à des signes évocateurs d’un incident pendant la transfusion ?',a:['Accélérer le débit','Arrêter ou suspendre immédiatement la transfusion selon le protocole','Attendre 15 minutes','Changer uniquement la tubulure'],correct:1,why:'La transfusion doit être interrompue sans délai selon le protocole local, tout en évaluant le patient et en alertant le médecin.'},
 {q:'Que signifie RAI ?',a:['Réaction allergique immédiate','Recherche d’agglutinines irrégulières','Registre annuel des incidents','Réserve autorisée injectable'],correct:1,why:'La RAI recherche des anticorps susceptibles de réagir contre des globules rouges étrangers.'},
 {q:'Quel tableau oriente davantage vers un TRALI ?',a:['Dyspnée aiguë et hypoxémie','Prurit isolé','Urines foncées sans dyspnée','Céphalée isolée'],correct:0,why:'Le TRALI se manifeste principalement par une atteinte respiratoire aiguë. Le diagnostic appartient à l’équipe médicale.'},
 {q:'Pourquoi vérifier l’identité au lit du patient ?',a:['Pour compléter le dossier plus tard','Pour prévenir une erreur receveur-produit','Pour accélérer la transfusion','Uniquement à la première transfusion'],correct:1,why:'La concordance stricte entre patient, prescription, documents et produit est une barrière essentielle contre l’erreur.'},
 {q:'L’hémovigilance concerne uniquement les réactions graves.',a:['Vrai','Faux'],correct:1,why:'Elle couvre la surveillance et la déclaration des événements indésirables liés à la chaîne transfusionnelle selon les règles applicables.'},
 {q:'Quel produit a pour rôle principal de restaurer la capacité de transport de l’oxygène ?',a:['Plasma','CGR','Concentré plaquettaire','Sérum physiologique'],correct:1,why:'Les concentrés de globules rouges apportent les cellules qui transportent l’oxygène.'},
 {q:'Les règles de compatibilité du plasma sont identiques à celles des CGR.',a:['Vrai','Faux'],correct:1,why:'Les règles diffèrent selon le composant. Il ne faut jamais transposer automatiquement celles des CGR au plasma.'},
 {q:'Quel élément doit être contrôlé immédiatement avant l’acte ?',a:['Uniquement le nom du service','L’identité du patient et la concordance avec le produit','Uniquement la couleur de la poche','Le groupe verbalement annoncé par le patient seulement'],correct:1,why:'L’identitovigilance et la concordance patient–documents–produit constituent une barrière de sécurité essentielle.'},
 {q:'Une dyspnée apparue pendant la transfusion doit être considérée comme :',a:['Un signe d’alerte','Un effet toujours bénin','Un motif pour accélérer la poche','Un signe sans lien possible'],correct:0,why:'Toute dyspnée pendant la transfusion doit déclencher une évaluation immédiate et l’application du protocole local.'},
 {q:'Quel tableau évoque davantage une réaction allergique simple ?',a:['Prurit et urticaire isolés','Douleur lombaire et urines foncées','Crépitants et hypertension','Fièvre à 40 °C avec choc'],correct:0,why:'Prurit et urticaire sont des signes fréquents d’une réaction allergique, mais une aggravation respiratoire ou hémodynamique doit être recherchée.'},
 {q:'Après un incident, la traçabilité peut-elle être différée indéfiniment ?',a:['Oui','Non'],correct:1,why:'L’événement, sa chronologie, le produit et les actions réalisées doivent être tracés selon le circuit institutionnel.'},
 {q:'Quel incident correspond à une surcharge circulatoire associée à la transfusion ?',a:['TRALI','TACO','RAI','ABO'],correct:1,why:'TACO désigne la surcharge circulatoire associée à la transfusion.'},
 {q:'Lors d’une suspicion d’incident, faut-il vérifier à nouveau le produit et l’identité ?',a:['Oui','Non, jamais'],correct:0,why:'Cette nouvelle vérification fait partie des actions immédiates essentielles, avec l’évaluation clinique et l’alerte.'},
 {q:'Quel signe peut accompagner une réaction hémolytique aiguë ?',a:['Douleur lombaire','Myopie','Hoquet isolé','Prurit ancien sans changement'],correct:0,why:'Douleur lombaire, fièvre, frissons, hypotension ou urines foncées peuvent notamment alerter.'},
 {q:'Le site peut-il remplacer le protocole transfusionnel de votre établissement ?',a:['Oui, dans tous les cas','Uniquement de nuit','Non','Seulement pour les étudiants'],correct:2,why:'Cette plateforme est pédagogique. Les procédures locales, recommandations professionnelles et décisions médicales restent la référence.'}
];
const scenarios = [
 {title:'Frissons après un CGR',body:'Quinze minutes après le début d’un CGR : frissons, 39 °C, douleur lombaire et tachycardie.',vitals:['T° 39 °C','FC 118/min','TA 92/58'],q:'Quelle est votre première action ?',options:['Ralentir simplement le débit','Arrêter la transfusion et alerter selon le protocole','Administrer le CGR jusqu’au bout','Attendre le prochain relevé'],correct:1,explain:'Ce tableau impose une interruption immédiate, l’évaluation du patient, le maintien de l’abord selon le protocole, les vérifications d’identité et l’alerte médicale.'},
 {title:'Dyspnée aiguë',body:'Pendant une transfusion de plasma : dyspnée brutale, désaturation et détresse respiratoire.',vitals:['SpO₂ 84 %','FR 32/min','T° 37,5 °C'],q:'Que faut-il faire en priorité ?',options:['Poursuivre lentement','Arrêter la transfusion, appeler immédiatement et prendre en charge l’urgence','Faire marcher le patient','Noter l’événement en fin de poste'],correct:1,explain:'Une détresse respiratoire est une urgence. TRALI, TACO ou autre cause doivent être évalués par l’équipe médicale.'},
 {title:'Urticaire isolée',body:'Dix minutes après le début de plaquettes : plaques d’urticaire et prurit, sans dyspnée ni hypotension.',vitals:['SpO₂ 98 %','TA 126/74','T° 37,1 °C'],q:'Quelle conduite initiale est la plus sûre ?',options:['Ignorer les signes','Suspendre la transfusion, évaluer et alerter selon le protocole','Retirer tout accès veineux','Faire sortir le patient'],correct:1,explain:'Même isolés, les signes doivent être pris en compte, la transfusion suspendue et le patient réévalué conformément au protocole local.'},
 {title:'Suspicion de surcharge',body:'Patient fragile présentant dyspnée, hypertension et crépitants après une transfusion rapide.',vitals:['SpO₂ 88 %','TA 178/96','FR 29/min'],q:'Quel incident doit notamment être évoqué ?',options:['TACO','Réaction cutanée simple','Erreur de prélèvement uniquement','RAI positive'],correct:0,explain:'La surcharge circulatoire (TACO) doit être évoquée. Arrêter la transfusion et déclencher la prise en charge urgente.'},
 {title:'Fièvre et hypotension',body:'Pendant des plaquettes : fièvre élevée, frissons intenses et chute tensionnelle.',vitals:['T° 40 °C','TA 78/45','FC 132/min'],q:'Quelle hypothèse grave faut-il rechercher ?',options:['Fatigue simple','Contamination bactérienne / réaction infectieuse','Carence en fer','Réaction retardée bénigne'],correct:1,explain:'Une réaction infectieuse sévère est possible. Interrompre la transfusion, alerter et lancer les investigations prévues localement.'}
];
const state = JSON.parse(localStorage.getItem('ta-state') || '{"completed":[],"quizScore":0,"started":false,"minutes":0}');
const save=()=>localStorage.setItem('ta-state',JSON.stringify(state));
const pct=()=>Math.round(state.completed.length/modules.length*100);
const statusFor=id=>state.completed.includes(id)?'done':(state.started&&id===modules.find(m=>!state.completed.includes(m.id))?.id?'current':'');
function moduleCards(items=modules){return items.map((m)=>{const i=modules.indexOf(m);return `<article class="card module-card"><div class="module-number"><span>MODULE ${String(i+1).padStart(2,'0')}</span><span class="status-pill ${statusFor(m.id)}">${statusFor(m.id)==='done'?'✓ Terminé':statusFor(m.id)==='current'?'En cours':m.duration}</span></div><div class="module-icon" aria-hidden="true">${m.icon}</div><h3>${m.title}</h3><p>${m.desc}</p><a href="#module/${m.id}">${statusFor(m.id)==='done'?'Revoir le module':'Ouvrir le module'} →</a></article>`}).join('')}
function home(){return `<div class="view"><section class="hero"><div class="hero-grid"><div><span class="eyebrow" style="color:#6dd9e3">FORMATION • SÉCURITÉ TRANSFUSIONNELLE</span><h1>Décider avec méthode.<br>Agir avec vigilance.</h1><p>Un parcours clair et interactif pour reconnaître les produits sanguins, sécuriser chaque contrôle et savoir réagir face aux signes d’alerte.</p><div class="hero-actions"><a class="button primary" href="#formation" data-start>${state.started?'Reprendre ma formation':'Commencer la formation'} <span>→</span></a><a class="button secondary" href="#cas">Tester un scénario</a></div></div><div class="hero-stat"><div class="ring" style="--progress:${pct()}%"><span>${pct()}%<small>PROGRESSION</small></span></div><div class="stat-row"><div><strong>6</strong><small>MODULES</small></div><div><strong>2 h 25</strong><small>DURÉE</small></div><div><strong>${state.quizScore||'—'}</strong><small>SCORE</small></div></div></div></div></section><div class="section-head"><div><span class="eyebrow">PARCOURS GUIDÉ</span><h2>Les essentiels, dans le bon ordre</h2><p>Chaque module associe notions clés, vigilance et vérification des acquis.</p></div><a href="#formation" class="button ghost">Voir tout le parcours</a></div><section class="card-grid">${moduleCards(modules.slice(0,3))}</section><div class="section-head"><div><span class="eyebrow">OUTILS PÉDAGOGIQUES</span><h2>S’entraîner, mémoriser, retrouver</h2></div></div><section class="feature-grid"><a class="feature" href="#cas" style="text-decoration:none"><span>◇</span><h3>Cas pratiques</h3><p>5 situations cliniques commentées.</p></a><a class="feature" href="#fiches" style="text-decoration:none"><span>▣</span><h3>Fiches mémos</h3><p>Les repères essentiels, imprimables.</p></a><a class="feature" href="#glossaire" style="text-decoration:none"><span>A</span><h3>Glossaire</h3><p>Les termes à connaître sans jargon.</p></a><a class="feature" href="#ressources" style="text-decoration:none"><span>↗</span><h3>Sources officielles</h3><p>Références datées et vérifiables.</p></a></section></div>`}
function formation(){return `<div class="view"><header class="page-head"><span class="eyebrow">FORMATION</span><h1>Votre parcours pédagogique</h1><p>Six modules progressifs • environ 2 h 25 • progression enregistrée sur cet appareil</p></header><section class="card-grid">${moduleCards()}</section><div class="section-head"><div><span class="eyebrow">REPÈRE</span><h2>Chaîne de sécurité transfusionnelle</h2></div></div><div class="flow" aria-label="Étapes de la chaîne transfusionnelle">${['Donneur','Collecte','Préparation','Qualification','Transport','Réception','Contrôles','Transfusion','Surveillance','Hémovigilance'].map((x,i)=>`<span class="flow-item">${x}</span>${i<9?'<span class="flow-arrow">→</span>':''}`).join('')}</div></div>`}
function moduleView(id){const m=modules.find(x=>x.id===id)||modules[0];let body='';
 if(id==='fondamentaux') body=`<div class="takeaway"><strong>À retenir</strong><ul><li>La transfusion est un acte médical apportant un composant sanguin par voie veineuse.</li><li>Chaque étape repose sur l’identification, la concordance, la traçabilité et la surveillance.</li><li>La sécurité est collective : prescripteur, laboratoire, délivrance et équipe au lit du patient.</li></ul></div><h2>Une chaîne sans rupture</h2><p>Du don à la surveillance du receveur, chaque transmission d’information constitue une barrière de sécurité. L’identité du patient et celle du produit doivent rester fiables et vérifiables à chaque étape.</p><div class="flow">${['Donneur','Collecte','Qualification','Délivrance','Contrôle','Transfusion','Surveillance'].map((x,i)=>`<span class="flow-item">${x}</span>${i<6?'<span class="flow-arrow">→</span>':''}`).join('')}</div>`;
 if(id==='psl') body=`<div class="card-grid"><article class="card product-card"><div class="product-visual">🩸</div><h3>Concentrés de globules rouges</h3><ul><li>Transport de l’oxygène</li><li>Compatibilité érythrocytaire essentielle</li><li>Conservation et indications selon référentiels en vigueur</li></ul></article><article class="card product-card plasma"><div class="product-visual">◒</div><h3>Plasma</h3><ul><li>Apport de facteurs plasmatiques</li><li>Compatibilité ABO spécifique</li><li>Décongélation et délais selon procédure</li></ul></article><article class="card product-card platelets"><div class="product-visual">✦</div><h3>Concentrés plaquettaires</h3><ul><li>Soutien de l’hémostase primaire</li><li>Conservation sous conditions contrôlées</li><li>Vigilance infectieuse et clinique</li></ul></article></div>`;
 if(id==='compatibilite') body=`<div class="takeaway"><strong>À retenir</strong><p>La compatibilité dépend du type de produit. Ne transposez jamais automatiquement les règles des CGR au plasma.</p></div><h2>Compatibilité ABO simplifiée — CGR</h2><div class="table-wrap"><table class="compat-table"><thead><tr><th>Receveur</th><th>O</th><th>A</th><th>B</th><th>AB</th></tr></thead><tbody><tr><th>O</th><td class="yes">Oui</td><td>Non</td><td>Non</td><td>Non</td></tr><tr><th>A</th><td class="yes">Oui</td><td class="yes">Oui</td><td>Non</td><td>Non</td></tr><tr><th>B</th><td class="yes">Oui</td><td>Non</td><td class="yes">Oui</td><td>Non</td></tr><tr><th>AB</th><td class="yes">Oui</td><td class="yes">Oui</td><td class="yes">Oui</td><td class="yes">Oui</td></tr></tbody></table></div><p class="warning"><strong>Point de vigilance :</strong> ce tableau est un support pédagogique simplifié pour les CGR. Appliquer les règles, qualifications et protocoles de l’établissement.</p>`;
 if(id==='securisation') body=`<div class="takeaway"><strong>Objectif</strong><p>Créer une pause de sécurité structurée immédiatement avant l’acte.</p></div><div class="checklist">${['Vérifier l’identité du patient selon la procédure','Contrôler la prescription','Vérifier la concordance des documents','Consulter les résultats immuno-hématologiques requis','Identifier le PSL et son numéro','Contrôler l’intégrité et la date de péremption','Vérifier la compatibilité applicable','Réaliser les contrôles réglementaires','Relever les constantes de référence et organiser la surveillance'].map((x,i)=>`<label class="check-item"><input type="checkbox" data-check="${i}"><span>${x}</span></label>`).join('')}</div>`;
 if(id==='incidents') body=`<div class="warning"><strong>Réflexe commun :</strong> devant tout signe anormal, interrompre ou suspendre la transfusion selon le protocole, évaluer le patient, conserver un abord veineux selon prescription/protocole, vérifier identité et produit, alerter le médecin et tracer.</div><h2>Repérer les principaux tableaux</h2><div class="incident-list">${incidents.map(x=>`<details class="incident"><summary>${x.name}<span class="alert-pill ${x.cls}">${x.level}</span></summary><div class="incident-content"><div><strong>Définition</strong><p>${x.definition}</p></div><div><strong>Signes évocateurs</strong><p>${x.signs}</p></div></div></details>`).join('')}</div>`;
 if(id==='hemovigilance') body=`<div class="takeaway"><strong>À retenir</strong><p>L’hémovigilance vise à surveiller, évaluer et prévenir les événements indésirables sur toute la chaîne transfusionnelle.</p></div><h2>Circuit pédagogique d’un signalement</h2><div class="decision">${['Repérer et sécuriser le patient','Alerter les interlocuteurs prévus localement','Recueillir les éléments et prélèvements nécessaires','Tracer le produit, le patient et la chronologie','Déclarer selon le circuit d’hémovigilance','Analyser et mettre en œuvre les actions préventives'].map((x,i)=>`<div class="decision-step"><b>${i+1}</b><span>${x}</span></div>`).join('')}</div>`;
 return `<div class="view"><header class="page-head"><a href="#formation" style="color:var(--blue);text-decoration:none">← Retour au parcours</a><h1>${m.title}</h1><p>${m.desc} • ${m.duration}</p></header><article class="lesson">${body}<div class="warning" style="margin-top:24px"><strong>Cadre d’utilisation :</strong> vérifier les recommandations et procédures institutionnelles en vigueur. Ce contenu ne remplace ni une décision médicale ni un protocole officiel.</div><div style="display:flex;gap:12px;justify-content:flex-end;margin-top:24px;flex-wrap:wrap"><button class="button ghost" onclick="window.print()">Imprimer</button><button class="button primary" data-complete="${id}">${state.completed.includes(id)?'✓ Module terminé':'Marquer comme terminé'}</button></div></article></div>`}
function casesView(){return `<div class="view"><header class="page-head"><span class="eyebrow">ENTRAÎNEMENT</span><h1>Simulateur d’incident transfusionnel</h1><p>Analysez la situation, choisissez la première action puis consultez l’explication.</p></header><div id="scenario-zone"></div></div>`}
let scenarioIndex=0;function renderScenario(){const z=document.querySelector('#scenario-zone');if(!z)return;const s=scenarios[scenarioIndex];z.innerHTML=`<article class="card quiz-card"><span class="question-count">SCÉNARIO ${scenarioIndex+1} / ${scenarios.length}</span><h2>${s.title}</h2><p>${s.body}</p><div class="scenario-vitals">${s.vitals.map(v=>`<span class="vital">${v}</span>`).join('')}</div><h3>${s.q}</h3><div class="answers">${s.options.map((a,i)=>`<button class="answer" data-sanswer="${i}"><span>${String.fromCharCode(65+i)}.</span>${a}</button>`).join('')}</div><div id="scenario-feedback"></div></article>`;
 document.querySelectorAll('[data-sanswer]').forEach(b=>b.onclick=()=>{const i=+b.dataset.sanswer;document.querySelectorAll('[data-sanswer]').forEach((x,j)=>x.classList.add(j===s.correct?'correct':j===i?'wrong':''));document.querySelector('#scenario-feedback').innerHTML=`<div class="feedback"><strong>${i===s.correct?'Bonne réponse':'À revoir'}</strong><p>${s.explain}</p><button class="button primary" id="next-scenario">${scenarioIndex<scenarios.length-1?'Scénario suivant':'Recommencer'}</button></div>`;document.querySelector('#next-scenario').onclick=()=>{scenarioIndex=(scenarioIndex+1)%scenarios.length;renderScenario()}})}
function quizView(){return `<div class="view"><header class="page-head"><span class="eyebrow">ÉVALUATION</span><h1>Quiz final</h1><p>15 questions couvrent les repères essentiels. Un score de 80 % valide l’évaluation.</p></header><div id="quiz-zone"></div></div>`}
let quizIndex=0,quizPoints=0;function renderQuiz(){const z=document.querySelector('#quiz-zone');if(!z)return;const q=quiz[quizIndex];z.innerHTML=`<article class="card quiz-card"><span class="question-count">QUESTION ${quizIndex+1} / ${quiz.length}</span><h2>${q.q}</h2><div class="answers">${q.a.map((a,i)=>`<button class="answer" data-qanswer="${i}"><span>${String.fromCharCode(65+i)}.</span>${a}</button>`).join('')}</div><div id="quiz-feedback"></div></article>`;document.querySelectorAll('[data-qanswer]').forEach(b=>b.onclick=()=>{const i=+b.dataset.qanswer;document.querySelectorAll('[data-qanswer]').forEach((x,j)=>{x.disabled=true;x.classList.add(j===q.correct?'correct':j===i?'wrong':'')});if(i===q.correct)quizPoints++;document.querySelector('#quiz-feedback').innerHTML=`<div class="feedback"><strong>${i===q.correct?'Bonne réponse':'Réponse incorrecte'}</strong><p>${q.why}</p><button class="button primary" id="next-question">${quizIndex<quiz.length-1?'Question suivante':'Voir mon résultat'}</button></div>`;document.querySelector('#next-question').onclick=()=>{if(quizIndex<quiz.length-1){quizIndex++;renderQuiz()}else{const score=Math.round(quizPoints/quiz.length*100);state.quizScore=score;save();z.innerHTML=`<article class="card quiz-card"><span class="eyebrow">RÉSULTAT</span><h2>${score>=80?'Évaluation validée':'Poursuivez votre révision'}</h2><p style="font-size:44px;font-weight:850;margin:.5rem 0">${score} %</p><p>${quizPoints} bonne(s) réponse(s) sur ${quiz.length}. ${score>=80?'Bravo, vos acquis essentiels sont solides.':'Relisez les modules Incidents et Sécurisation puis réessayez.'}</p><button class="button primary" id="retry">Recommencer</button></article>`;document.querySelector('#retry').onclick=()=>{quizIndex=0;quizPoints=0;renderQuiz()};updateProgress()}}})}
function fiches(){const cards=[['Compatibilité ABO','Tableau simplifié pour les CGR et points de vigilance.'],['Contrôle avant transfusion','Neuf vérifications essentielles avant l’acte.'],['Signes d’alerte','Fièvre, frissons, dyspnée, douleur, hypotension et signes cutanés.'],['Conduite face à un incident','Réflexes immédiats, alerte, investigations et traçabilité.'],['TRALI / TACO','Repères comparatifs pour orienter l’évaluation médicale.'],['Principaux PSL','CGR, plasma et plaquettes en un coup d’œil.']];return `<div class="view"><header class="page-head"><span class="eyebrow">MÉMOS</span><h1>Fiches pratiques</h1><p>Des synthèses visuelles à consulter ou à imprimer.</p></header><section class="memo-grid">${cards.map((c,i)=>`<article class="memo"><span class="eyebrow">FICHE ${String(i+1).padStart(2,'0')}</span><h2>${c[0]}</h2><p>${c[1]}</p><button class="button ghost" onclick="window.print()">Imprimer la fiche</button></article>`).join('')}</section></div>`}
function glossaryView(){return `<div class="view"><header class="page-head"><span class="eyebrow">RÉFÉRENTIEL</span><h1>Glossaire</h1><p>Recherchez rapidement une notion clé.</p></header><div class="global-search" style="max-width:700px;margin-bottom:20px"><span>⌕</span><input id="term-search" type="search" placeholder="Ex. RAI, TRALI, compatibilité…" aria-label="Rechercher dans le glossaire"></div><dl class="glossary-list" id="glossary-list">${glossary.map(g=>`<div class="term"><dt>${g[0]}</dt><dd>${g[1]}</dd></div>`).join('')}</dl></div>`}
function resources(){return `<div class="view"><header class="page-head"><span class="eyebrow">SOURCES</span><h1>Ressources et références</h1><p>Les recommandations évoluent : contrôlez la date et la version avant tout usage professionnel.</p></header><div class="two-col"><section class="card"><h2>Références officielles</h2><div class="incident-list"><article class="resource"><span class="resource-icon">PDF</span><div><strong>HAS — Fiche d’information patient : la transfusion sanguine</strong><small>Décembre 2025 • consulté en septembre 2026</small></div><a href="https://www.has-sante.fr/upload/docs/application/pdf/2026-03/23-fiche_d_information_patient_-_la_transfusion_sanguine.pdf" target="_blank" rel="noopener">Ouvrir ↗</a></article><article class="resource"><span class="resource-icon">ANSM</span><div><strong>Produits sanguins labiles et hémovigilance</strong><small>Portail institutionnel • vérifier la version en vigueur</small></div><a href="https://ansm.sante.fr" target="_blank" rel="noopener">Ouvrir ↗</a></article><article class="resource"><span class="resource-icon">EFS</span><div><strong>Établissement français du sang</strong><small>Informations sur le sang et ses composants</small></div><a href="https://www.efs.sante.fr" target="_blank" rel="noopener">Ouvrir ↗</a></article><article class="resource"><span class="resource-icon">CSP</span><div><strong>Code de la santé publique</strong><small>Articles et réglementation en vigueur</small></div><a href="https://www.legifrance.gouv.fr/codes/id/LEGITEXT000006072665/" target="_blank" rel="noopener">Ouvrir ↗</a></article></div></section><section class="card ai-box"><span class="eyebrow" style="color:#75e7ec">ASSISTANT PÉDAGOGIQUE</span><h2>Posez votre question</h2><p>Essayez « Quelle différence entre TRALI et TACO ? » ou « Que signifie RAI ? »</p><textarea id="ai-question" placeholder="Écrivez votre question…"></textarea><button class="button secondary" id="ask-ai">Obtenir un repère pédagogique</button><div id="ai-answer"></div></section></div></div>`}
function dashboard(){return `<div class="view"><header class="page-head"><span class="eyebrow">MON PARCOURS</span><h1>Tableau de bord apprenant</h1><p>Votre progression est enregistrée dans ce navigateur.</p></header><section class="metric-grid"><article class="metric"><small>Progression</small><strong>${pct()} %</strong><div class="progress-track"><i style="width:${pct()}%"></i></div></article><article class="metric"><small>Modules terminés</small><strong>${state.completed.length} / ${modules.length}</strong></article><article class="metric"><small>Score global</small><strong>${state.quizScore?state.quizScore+' %':'—'}</strong></article><article class="metric"><small>Temps estimé suivi</small><strong>${state.completed.length*22} min</strong></article></section><section class="card dashboard-list"><h2>Détail du parcours</h2>${modules.map((m,i)=>`<div class="dash-row"><span class="dash-num">${i+1}</span><div><strong>${m.title}</strong><small>${m.duration}</small></div><span class="status-pill ${statusFor(m.id)}">${statusFor(m.id)==='done'?'✓ Terminé':statusFor(m.id)==='current'?'En cours':'À commencer'}</span></div>`).join('')}</section></div>`}
function route(){const hash=location.hash.slice(1)||'accueil';const [page,id]=hash.split('/');document.querySelector('#main').innerHTML=page==='accueil'?home():page==='formation'?formation():page==='module'?moduleView(id):page==='cas'?casesView():page==='quiz'?quizView():page==='fiches'?fiches():page==='glossaire'?glossaryView():page==='ressources'?resources():page==='parcours'?dashboard():home();document.querySelectorAll('.nav-link').forEach(a=>a.classList.toggle('active',a.dataset.page===(page==='module'?'formation':page)));document.querySelector('#sidebar').classList.remove('open');document.querySelector('#menu-toggle').setAttribute('aria-expanded','false');window.scrollTo(0,0);bindView();updateProgress()}
function bindView(){document.querySelectorAll('[data-start]').forEach(x=>x.onclick=()=>{state.started=true;save()});document.querySelectorAll('[data-complete]').forEach(x=>x.onclick=()=>{const id=x.dataset.complete;if(!state.completed.includes(id))state.completed.push(id);state.started=true;save();x.textContent='✓ Module terminé';toast('Progression enregistrée');updateProgress()});document.querySelectorAll('[data-check]').forEach(x=>{x.checked=localStorage.getItem('check-'+x.dataset.check)==='1';x.onchange=()=>localStorage.setItem('check-'+x.dataset.check,x.checked?'1':'0')});if(document.querySelector('#scenario-zone'))renderScenario();if(document.querySelector('#quiz-zone')){quizIndex=0;quizPoints=0;renderQuiz()}const ts=document.querySelector('#term-search');if(ts)ts.oninput=()=>{const q=ts.value.toLowerCase();document.querySelector('#glossary-list').innerHTML=glossary.filter(g=>g.join(' ').toLowerCase().includes(q)).map(g=>`<div class="term"><dt>${g[0]}</dt><dd>${g[1]}</dd></div>`).join('')||'<p class="empty">Aucun terme trouvé.</p>'};const ask=document.querySelector('#ask-ai');if(ask)ask.onclick=answerQuestion}
function answerQuestion(){const q=document.querySelector('#ai-question').value.toLowerCase();let a;if(q.includes('trali')||q.includes('taco'))a='<strong>TRALI ou TACO ?</strong><p>Les deux peuvent provoquer une détresse respiratoire. Le TRALI correspond à une atteinte pulmonaire aiguë associée à la transfusion ; le TACO à une surcharge circulatoire. La tension, les signes de surcharge, le bilan clinique et les examens orientent l’équipe médicale.</p><a href="#module/incidents">Voir le module Incidents →</a>';else if(q.includes('rai'))a='<strong>RAI</strong><p>La recherche d’agglutinines irrégulières détecte des anticorps susceptibles de réagir contre des globules rouges étrangers.</p><a href="#module/compatibilite">Voir le module Compatibilité →</a>';else if(q.includes('signe')||q.includes('alerte')||q.includes('dysp'))a='<strong>Signes à surveiller</strong><p>Fièvre, frissons, dyspnée, douleur, hypotension, urticaire, rougeurs, nausées ou urines foncées doivent alerter. En pratique, suivez immédiatement le protocole de votre établissement.</p><a href="#module/incidents">Voir le module Incidents →</a>';else a='<strong>Repère pédagogique</strong><p>Consultez le module le plus proche de votre question ou utilisez la recherche globale. Pour une situation réelle, appliquez le protocole de l’établissement et contactez les professionnels responsables.</p>';document.querySelector('#ai-answer').innerHTML=`<div class="ai-answer">${a}<p><small>Cet assistant de démonstration ne fournit pas de décision clinique.</small></p></div>`}
function updateProgress(){document.querySelector('#side-progress').style.width=pct()+'%';document.querySelector('#side-progress-label').textContent=pct()+' % complété'}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
document.querySelector('#main-nav').innerHTML=nav.map(n=>`<a class="nav-link" data-page="${n[0]}" href="#${n[0]}"><span class="nav-icon" aria-hidden="true">${n[1]}</span>${n[2]}</a>`).join('');
document.querySelector('#menu-toggle').onclick=()=>{const s=document.querySelector('#sidebar');s.classList.toggle('open');document.querySelector('#menu-toggle').setAttribute('aria-expanded',s.classList.contains('open'))};
const globalSearch=document.querySelector('#global-search'),results=document.querySelector('#search-results');const searchIndex=[...modules.map(m=>({title:m.title,desc:m.desc,url:'#module/'+m.id})),...incidents.map(i=>({title:i.name,desc:i.signs,url:'#module/incidents'})),...glossary.map(g=>({title:g[0],desc:g[1],url:'#glossaire'}))];globalSearch.oninput=()=>{const q=globalSearch.value.trim().toLowerCase();if(q.length<2){results.hidden=true;return}const found=searchIndex.filter(x=>(x.title+' '+x.desc).toLowerCase().includes(q)).slice(0,6);results.innerHTML=found.map(x=>`<a class="search-result" href="${x.url}"><strong>${x.title}</strong><small>${x.desc}</small></a>`).join('')||'<p class="empty">Aucun résultat. Essayez un autre terme.</p>';results.hidden=false};globalSearch.onkeydown=e=>{if(e.key==='Escape')results.hidden=true};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();globalSearch.focus()}});document.addEventListener('click',e=>{if(!e.target.closest('.global-search'))results.hidden=true});window.addEventListener('hashchange',route);route();
